<a href="https://colab.research.google.com/github/Johanhms/Learning_Python/blob/main/DataScience_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Types of Variable**

In [ ]:
counter = 0
while counter < 12:
  print(counter)
  counter = counter + 1


0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in range(5):
  print("Hello")

Hello
Hello
Hello
Hello
Hello


In [ ]:
for i in range(5):
  print("Hello: ", i)

Hello:  0
Hello:  1
Hello:  2
Hello:  3
Hello:  4


In [ ]:
mylist = [10,100,1000]

In [ ]:
for j in mylist:
  print("j is: ", j)

j is:  10
j is:  100
j is:  1000


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
randn()

0.966564236679124

In [ ]:
x = randn()
if x > 1:
  answer = "Greater than 1"
print(x)
print(answer)

2.2629430979297833
Greater than 1


In [ ]:
x = randn()
if x > 1:
  answer = "Greatter than 1"
else:
  answer = "Less than 1"
  print(x)
  print(answer)

-1.9342967483250317
Less than 1


In [ ]:
x = randn()
if x > 1:
  answer = "Greater than 1"
else:
    if x >=-1:
      answer = "Between -1 and 1"
    else:
      answer = "Less than -1"
print(x)
print(answer)

-0.10769703913430084
Between -1 and 1


In [ ]:
x = randn()
if x > 1:
  answer = "Greater than 1"
elif x >= -1:
  answer = "Between -1 and 1"
else:
  answer = "Less than -1"
print(x)
print(answer)

-0.06348372607557588
Between -1 and 1


In [ ]:
counter  = 0
while counter < 4:
  print("abra")
  counter = counter + 1

abra
abra
abra
abra


## **Fundamental of Python**

In [ ]:
w = list(range(100,200,10))

In [ ]:
w[0]

100

In [ ]:
len(w)

10

In [ ]:
w[-3]

170

In [ ]:
w[-1]


190

In [ ]:
w[9]

190

In [ ]:
w[2] = 2

In [ ]:
w

[100, 110, 2, 130, 140, 150, 160, 170, 180, 190]

In [ ]:
w[::-1]

[190, 180, 170, 160, 150, 140, 130, 2, 110, 100]

In [ ]:
myList = list(range(20,31))

In [ ]:
len(myList)

11

In [ ]:
type(mylist)

list

In [ ]:
max(myList)

30

In [ ]:
a = np.array(myList)


In [ ]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
mylist.append(10)


In [ ]:
a.mean()

25.0



##**NumPy**



In [ ]:
import numpy as np

In [ ]:
np.random.randn(5,5)

array([[ 0.28600552, -0.00698919,  0.11737739, -0.79545267, -0.86386242],
       [-0.19657888, -0.02878489, -0.82736057, -0.93235976,  1.53398768],
       [ 0.8072843 , -0.09061811, -1.54337738, -0.07931692,  0.73794393],
       [-2.97725398,  0.47077131, -1.07683236, -0.68215316,  0.46343248],
       [-0.4833959 , -1.06943295, -0.87277726, -1.30180699,  0.79480352]])

In [ ]:
np.random.randn(4,4)

array([[-0.50029033,  0.66411011,  1.21526375,  0.56861005],
       [ 1.85149338,  1.32183528,  1.27003312,  0.67513848],
       [-0.93955876, -0.20891845,  0.48330774,  0.30052566],
       [ 1.57136681,  1.60203473, -0.56952179,  0.13164167]])

In [ ]:
np.random.randint(1,100,20)

array([59,  3, 50, 55, 16, 63, 71, 66,  8, 96, 27, 80, 85,  2, 59, 19,  5,
        9, 11, 93])

In [ ]:
arr = np.arange(25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.max()

24

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.03199268])

In [ ]:
np.random.randn(25)

array([ 0.03189229,  1.0766765 ,  1.45656705, -0.81478902,  0.36366752,
       -1.01283297,  0.66972331,  0.5980334 , -0.70453421, -0.51102667,
       -0.57396948, -0.14026153,  0.37977153, -0.69509101,  1.33694012,
       -0.10289016, -2.07650652,  0.25652841,  0.90723268,  0.96432598,
        0.29553267, -0.47350869,  3.10691375, -1.23224801, -2.35966532])

In [ ]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat [4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
np.sum(mat)

325

In [ ]:
mat.sum()

325

In [ ]:
mat.std()

7.211102550927978

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

##**Pandas**

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [ ]:
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.drop('new', axis = 1, inplace = True)

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.drop('E', axis= 0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [ ]:
df[df['W'] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['Z']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [ ]:
df[df['W']>0][['X','Y']]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [ ]:
boolser = df['W'] > 0

In [ ]:
result = df[boolser]
mycols = ['Y','X']
result[mycols]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [ ]:
df[(df['W'] > 0) & (df['Y'] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[(df['W'] > 0) | (df['Y'] > 1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [ ]:
df['States'] = newind

In [ ]:
df

W         X         Y         Z States
States                                               
CA      2.706850  0.628133  0.907969  0.503826     CA
NY      0.651118 -0.319318 -0.848077  0.605965     NY
WY     -2.018168  0.740122  0.528813 -0.589001     WY
OR      0.188695 -0.758872 -0.933237  0.955057     OR
CO      0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df = df.set_index('States')

KeyError: "None of ['States'] are in the columns"

In [ ]:
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [ ]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [ ]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [ ]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [ ]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [ ]:
df.index.names = ['Groups','Num']

In [ ]:
df

A         B
Groups Num                    
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [ ]:
df.loc['G2'].loc[2]['B']

0.07295967531703869

In [ ]:
df.xs('G1')

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [ ]:
df.xs(1,level='Num')

A         B
Groups                    
G1      0.302665  1.693723
G2      0.166905  0.184502

In [ ]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [ ]:
byCompany = df.groupby('Company')

In [ ]:
byCompany['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [ ]:
byCompany['Sales'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [ ]:
df.groupby('Company').sum().loc['FB']

Person    CarlSarah
Sales           593
Name: FB, dtype: object

In [ ]:
df.groupby('Company').describe ()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
df1 = pd.D

In [ ]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [ ]:
df

[                               Bank Name               City         State  \
 0                   Pulaski Savings Bank            Chicago      Illinois   
 1     The First National Bank of Lindsay            Lindsay      Oklahoma   
 2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania   
 3                          Citizens Bank           Sac City          Iowa   
 4               Heartland Tri-State Bank            Elkhart        Kansas   
 5                    First Republic Bank      San Francisco    California   
 6                         Signature Bank           New York      New York   
 7                    Silicon Valley Bank        Santa Clara    California   
 8                      Almena State Bank             Almena        Kansas   
 9             First City Bank of Florida  Fort Walton Beach       Florida   
 
     Cert                 Aquiring Institution      Closing Date  \
 0  28611                      Millennium Bank  January 17, 2025   
 1  

In [ ]:
type(df)

list

In [ ]:
df[0].head()

Bank Name          City         State   Cert  \
0                   Pulaski Savings Bank       Chicago      Illinois  28611   
1     The First National Bank of Lindsay       Lindsay      Oklahoma   4134   
2  Republic First Bank dba Republic Bank  Philadelphia  Pennsylvania  27332   
3                          Citizens Bank      Sac City          Iowa   8758   
4               Heartland Tri-State Bank       Elkhart        Kansas  25851   

                 Aquiring Institution      Closing Date  Fund  Sort ascending  
0                     Millennium Bank  January 17, 2025                 10548  
1  First Bank & Trust Co., Duncan, OK  October 18, 2024                 10547  
2   Fulton Bank, National Association    April 26, 2024                 10546  
3           Iowa Trust & Savings Bank  November 3, 2023                 10545  
4              Dream First Bank, N.A.     July 28, 2023                 10544

In [2]:
import pandas as pd

In [ ]:
 sal = pd.read_csv('Salaries.csv')

In [ ]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal['BasePay'].mean()

66325.4488404877

In [ ]:
sal['OvertimePay'].max()

245131.88

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
gropedbyY = sal.groupby('Year')

In [ ]:
gropedbyY

In [ ]:
gropedbyY['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [ ]:
sal.nunique()['JobTitle']

2159

In [ ]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [ ]:
sum(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1)


202

In [ ]:
def chief_string(title):
  if 'chief' in title.lower().split():
    return True
  else:
    return False

In [ ]:
sum(sal['JobTitle'].apply(lambda x : chief_string(x)))

477

In [ ]:
sal['title_len'] = sal['JobTitle'].apply(len)

In [ ]:
sal[['JobTitle','title_len']]

JobTitle  title_len
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY         46
1                      CAPTAIN III (POLICE DEPARTMENT)         31
2                      CAPTAIN III (POLICE DEPARTMENT)         31
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC         36
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)         44
...                                                ...        ...
148649                                       Custodian          9
148650                                    Not provided         12
148651                                    Not provided         12
148652                                    Not provided         12
148653                      Counselor, Log Cabin Ranch         26

[148654 rows x 2 columns]

In [ ]:
sal[['TotalPayBenefits','title_len']].corr()

TotalPayBenefits  title_len
TotalPayBenefits          1.000000  -0.036878
title_len                -0.036878   1.000000

In [5]:
ecom = pd.read_csv('Ecommerce Purchases')

In [6]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [11]:
ecom.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [12]:
ecom['Purchase Price'].mean()

50.347302

In [14]:
ecom['Purchase Price'].max()

99.99

In [15]:
ecom['Purchase Price'].min()

0.0

In [23]:
ecom[ecom['Language'] == 'en']['Language'].count()

1098

In [89]:
jobs_counts = ecom.groupby('Job')['Job'].count()


In [32]:
ecom[ecom['Job'] == 'Lawyer']['Job'].count()

30

In [39]:
ecom.groupby('AM or PM')['AM or PM'].count()

AM or PM
AM    4932
PM    5068
Name: AM or PM, dtype: int64

In [44]:
ecom.groupby('Job')['Job'].count().sort_values(ascending = False).head(5)

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Designer, jewellery                  27
Research officer, political party    27
Name: Job, dtype: int64

In [45]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [51]:
ecom[ecom['Lot'] == '90 WT']['Company']

513    Bright PLC
Name: Company, dtype: object

In [62]:
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [60]:
ecom.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [74]:
Purc = ecom[ecom['Purchase Price'] > 95]

In [75]:
Purc

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
9       3795 Dawson Extensions\nLake Tinafort, ID 88739  15 Ug       AM   
10        650 Elizabeth Park\nLake Maria, LA 13526-2530  65 Yn       PM   
23    25292 Shepherd Trail Apt. 798\nRussellmouth, S...  31 pS       PM   
35    93392 Webb Gardens Apt. 220\nLaurabury, AR 999...  37 om       AM   
...                                                 ...    ...      ...   
9885            82535 Gay Bypass\nNew Kathryn, AZ 05190  39 vm       PM   
9886  037 Kelsey Knolls Suite 020\nTorresmouth, UT 5...  56 SL       AM   
9934     52276 Smith Cliffs\nLake Vanessaview, AL 91791  40 nG       AM   
9958                   PSC 8781, Box 4214\nAPO AP 94478  72 Ez       AM   
9967            409 Holland Drives\nWhitetown, ME 78654  38 aX       AM   

                                           Browser Info  \
0     Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
9     Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...   
10    Mozilla/5.0 (iPod; U; CPU iPhone OS 4_1 like M...   
23    Mozilla/5.0 (compatible; MSIE 5.0; Windows 98;...   
35    Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...   
...                                                 ...   
9885  Mozilla/5.0 (Windows NT 5.2) AppleWebKit/5361 ...   
9886  Mozilla/5.0 (Windows NT 5.0) AppleWebKit/5320 ...   
9934  Opera/9.62.(Windows NT 5.0; sl-SI) Presto/2.9....   
9958  Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...   
9967  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   

                               Company       Credit Card CC Exp Date  \
0                      Martinez-Herman  6011929061123406       02/20   
9         Rivera, Buchanan and Ramirez     4396283918371       01/17   
10    Strickland, Michael and Gonzales   180036417827355       02/17   
23                            Cruz Inc      502010078983       02/23   
35                            Mora Ltd  6011049630969815       09/16   
...                                ...               ...         ...   
9885                      Phillips LLC      501816385980       07/26   
9886                    Thompson-Moore     4893575931765       09/17   
9934                          Clay LLC  5148775191773208       05/23   
9958        Logan, Anderson and Martin   210030902457830       08/24   
9967                     Singleton Inc   869944453111857       04/26   

      CC Security Code                  CC Provider  \
0                  900                 JCB 16 digit   
9                  931             American Express   
10                 754                      Voyager   
23                  60                VISA 13 digit   
35                 367                   Mastercard   
...                ...                          ...   
9885               584                     Discover   
9886               663                 JCB 16 digit   
9934               583                VISA 16 digit   
9958               597                      Maestro   
9967               602  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
9        qcoleman@hunt-huerta.com                      Forensic scientist   
10           ustewart@hotmail.com           Development worker, community   
23    ltaylor@gardner-meadows.com                      Field seismologist   
35         hgonzalez@mcdowell.com             Lecturer, further education   
...                           ...                                     ...   
9885    mitchellricky@hotmail.com                         Patent attorney   
9886     samanthasims@hotmail.com                           Social worker   
9934          popejames@yahoo.com               Consulting civil engineer   
9958       reynoldsrick@yahoo.com             Industrial/product designer   
9967             gina95@gmail.com              Television camera 

In [76]:
Amex = ecom[ecom['CC Provider'] == 'American Express']

In [84]:
ecom[(ecom['Purchase Price'] > 95) & (ecom['CC Provider'] == 'American Express')].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [92]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [96]:
ecom['CC Exp Date'].iloc[0][3:]

'20'

In [102]:
sum(ecom['CC Exp Date'].apply(lambda exp: exp[3:] == '25'))

1033

In [106]:
len(ecom['Email'].iloc[0])

17

In [108]:
example_email = ecom['Email'].iloc[0]

In [112]:
example_email.split('@')[1]

'yahoo.com'

In [115]:
ecom['Email'].apply(lambda email: email.split('@')[1]).value_counts().head(5)

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64